export const SpeciesFields = new Map([
  ['species', 'Species'],
  ['author', 'Author'],
  ['division', 'Division'],
  ['class', 'Class'],
  ['order', 'Order'],
  ['sflag', 'SFLAG'],
  ['stage', 'Stage'],
  ['trophy', 'Trophy'],
  ['formula', 'Formula'],
  ['geometricShape', 'Geometric shape'],
]);

export const SizeClassFields = new Map([
  ['sizeClassNo', 'Size class'],
  ['unit', 'Unit'],
  ['sizeRange', 'Size range'],
  ['length1', 'Length(l1), µm'],
  ['length2', 'Length(l2), µm'],
  ['width', 'Width(w), µm'],
  ['height', 'Height(h), µm'],
  ['diameter1', 'Diameter(d1), µm'],
  ['diameter2', 'Diameter(d2), µm'],
  ['noOfCellsPerCountingUnit', 'No. of cells/counting unit'],
  ['calculatedVolume', 'Calculated volume, µm3'],
  ['comment', 'Comment'],
  ['filament', 'Filament: length of cell (µm)'],
  ['calculatedCarbonPgPerCountingUnit','Calculated Carbon pg/counting unit'],
  ['commentOnCarbonCalculation', 'Comment on Carbon calculation'],
]);
