name: Build

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 14

            - name: Install Dependencies
              run: yarn install

            - name: Build
              run: yarn run build

            - name: Archive Artifact
              uses: actions/upload-artifact@v2
              with:
                name: nua-ui
                path: dist
